// <auto-generated />
namespace EnterwellApp.Presentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TabliceKorisnikaInicijalizacija : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabliceKorisnikaInicijalizacija));
        
        string IMigrationMetadata.Id
        {
            get { return "201808181013385_TabliceKorisnikaInicijalizacija"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
